STRING(TOLOWER "${CPACK_PACKAGE_NAME}" CPACK_PACKAGE_NAME)
# Replace blank lines with . control statement
STRING(REGEX REPLACE "^\\s*\n" "\n.\n" CPACK_DEBIAN_PACKAGE_DESCRIPTION ${CPACK_PACKAGE_DESCRIPTION})
SET(CPACK_DEBIAN_PACKAGE_SECTION "science")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINTER ${CPACK_PACKAGE_CONTACT})

## Add target for creating the compressed changelog
add_custom_command( OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/changelog.gz
  COMMAND gzip -c -n -9 -f  ${CMAKE_CURRENT_SOURCE_DIR}/CHANGELOG.md >  ${CMAKE_CURRENT_BINARY_DIR}/changelog.gz
  COMMENT "Creating compressed changelog."
  DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/CHANGELOG.md
)

add_custom_target(DEB_EXTRAS ALL
	DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/changelog.gz)

INSTALL( FILES ${CMAKE_CURRENT_BINARY_DIR}/changelog.gz
	DESTINATION "share/doc/${CPACK_PACKAGE_NAME}/"
# 	COMPONENT DEB_EXTRAS
)

INSTALL( FILES LICENSE.md
	RENAME copyright
	DESTINATION "share/doc/${CPACK_PACKAGE_NAME}/"
# 	COMPONENT DEB_EXTRAS
)


## Set Package Dependencies 
SET(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON) 
SET(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY ">=") 
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "gnuplot (>= 4.4)") 
IF (MORPHEUS_GUI) 
  MESSAGE(STATUS "Adding GUI dependencies" ) 
  SET(CPACK_DEBIAN_PACKAGE_DEPENDS  "${CPACK_DEBIAN_PACKAGE_DEPENDS}, libqt5sql5-sqlite") 
ENDIF() 
IF (MORPHEUS_GRAPHVIZ STREQUAL "Library") 
  MESSAGE(STATUS "Adding GraphVIZ dependencies" ) 
  SET(CPACK_DEBIAN_PACKAGE_DEPENDS "${CPACK_DEBIAN_PACKAGE_DEPENDS}, graphviz") 
ENDIF()
