
#DragNDrop package name
# SET(CPACK_DMG_VOLUME_NAME "${CPACK_PACKAGE_NAME}_${PROJECT_VERSION}")

#Bundle 
# SET(CPACK_BUNDLE_NAME "${CPACK_PACKAGE_NAME}")
# SET(CPACK_BUNDLE_PLIST "${CMAKE_CURRENT_BINARY_DIR}/gui/Info.plist")
