#!/bin/bash
TEST_BASE=$1
TEST_NUMBER=$2
SBML_LEVEL=$3
SBML_VERSION=$4
OUTPUT_DIR=$5

TEST_DIR=${TEST_BASE}/$TEST_NUMBER
SBML_MODEL=${TEST_NUMBER}-sbml-l${SBML_LEVEL}v${SBML_VERSION}.xml
MORPHEUS_MODEL=${TEST_NUMBER}-morpheus.xml

pushd $OUTPUT_DIR
morpheus-gui --convert $TEST_DIR/$SBML_MODEL $MORPHEUS_MODEL
morpheus $MORPHEUS_MODEL
popd
