MESSAGE(STATUS "Configuring environment for packaging Morpheus into ${CPACK_GENERATOR}")

## Here we setup specific parameters per generator -- No build here 

MESSAGE(STATUS "All COMPONENTS ${CPACK_COMPONENTS_ALL}")

IF(CPACK_GENERATOR STREQUAL "DEB")
  SET(CPACK_MONOLITHIC_INSTALL 1)
  SET(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")

  ## Include System Architecture into package name
#   FIND_PROGRAM(DPKG_PROGRAM dpkg DOC "dpkg package manager of Debian-based systems")
#   IF(DPKG_PROGRAM) 
#     EXECUTE_PROCESS( 
#       COMMAND ${DPKG_PROGRAM} --print-architecture 
#       OUTPUT_VARIABLE CPACK_DEBIAN_PACKAGE_ARCHITECTURE 
#       OUTPUT_STRIP_TRAILING_WHITESPACE 
#     )
#     STRING(APPEND CPACK_PACKAGE_FILE_NAME "_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")
#   ENDIF()

  IF(CPACK_PACKAGE_NAME_TAG) 
    STRING(APPEND CPACK_PACKAGE_FILE_NAME "~${CPACK_PACKAGE_NAME_TAG}") 
  ENDIF()

ELSEIF(CPACK_GENERATOR STREQUAL "Bundle")

  LIST(APPEND CPACK_COMPONENTS_ALL BUNDLE_EXTRAS)

ELSEIF(CPACK_GENERATOR STREQUAL "NSIS")
  
  SET(CPACK_MONOLITHIC_INSTALL 1)

ELSEIF(CPACK_GENERATOR STREQUAL "WIX")  
  SET(CPACK_WIX_PRODUCT_GUID "D80BAC6B-539F-4384-AD1B-FCDD8091DE76")
  SET(CPACK_WIX_UPGRADE_GUID ${CPACK_WIX_PRODUCT_GUID})
  SET(CPACK_WIX_PRODUCT_ICON "${CMAKE_CURRENT_SOURCE_DIR}/gui/icons/win/morpheus.ico")
  SET(CPACK_WIX_PROPERTY_ARPURLINFOABOUT ${CPACK_PACKAGE_HOMEPAGE} )
ENDIF()
