# Try to Find libSSH
#
#  LIBSSH_INCLUDE_DIR - where to find libssh.h, etc.
#  LIBSSH_LIBRARIES   - List of libraries.
#  LIBSSH_FOUND       - True if libSSH found.


IF (LIBSSH_INCLUDE_DIR)
  # Already in cache, be silent
  SET(LIBSSH_FIND_QUIETLY TRUE)
ENDIF (LIBSSH_INCLUDE_DIR)

FIND_PATH(LIBSSH_INCLUDE_DIR libssh.h PATH_SUFFIXES libssh)

SET(LIBSSH_NAMES ssh)
FIND_LIBRARY(LIBSSH_LIBRARY NAMES ${LIBSSH_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set LIBSSH_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBSSH DEFAULT_MSG LIBSSH_LIBRARY LIBSSH_INCLUDE_DIR)

IF(LIBSSH_FOUND)
  SET( LIBSSH_LIBRARIES ${LIBSSH_LIBRARY} )
ELSE(LIBSSH_FOUND)
  SET( LIBSSH_LIBRARIES )
ENDIF(LIBSSH_FOUND)

MARK_AS_ADVANCED( LIBSSH_LIBRARY LIBSSH_INCLUDE_DIR )
